### ISSUE TITLE
The questions about vocab.txt

### ISSUE THREAD

**Issue by LLMforScience** [lvkd84/GraphFP#1]
Hi, thank you for your work. 

`CNC[C@H]1Oc2ccccc2C(=O)N([C@H](C)CO)C[C@@H]1C	21	758`

`CNC[C@H]1Oc2ccccc2C(=O)N([C@H](C)CO)C[C@@H]1C` is the SMILES of fragment. 

I want to ask what are the meanings of "21" and "758" in the vocab.txt

**Comment by lvkd84** [comment]
Hi,

"21" is the size of the fragment. If you count the number of heavy atoms in the SMILES string, you'll find 21 of them.

"758" is the number of occurrence of this fragment during fragment mining from the pretraining dataset. Essentially, you can compare the frequencies of different fragments by comparing this number. The more frequent fragments will be prioritized during fragment graph construction.

The code is collected and adapted from Principal Subgraph Mining. You can also refer to their code here: [https://github.com/THUNLP-MT/PS-VAE](https://github.com/THUNLP-MT/PS-VAE)

Let me know if you have any further question.
